import ClientFooter from "@/components/client/client-footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LayoutHeader from "@/components/client/layout-header";

const inter = Inter({ subsets: ["cyrillic"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans`}>
        <LayoutHeader />
        {children}
        <ClientFooter />
      </body>
    </html>
  );
}
